version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: commitizen
    versions:
    - "> 3.1.0"
  - dependency-name: cz-conventional-changelog
    versions:
    - "> 2.1.0"
  - dependency-name: husky
    versions:
    - "> 1.2.0"
  - dependency-name: jest
    versions:
    - "> 24.4.0"
  - dependency-name: make-dir
    versions:
    - "> 1.3.0"
  - dependency-name: semantic-release
    versions:
    - "> 15.12.2"
  - dependency-name: ts-jest
    versions:
    - "> 24.0.1"
  - dependency-name: "@types/jest"
    versions:
    - "> 23.3.9"
  - dependency-name: "@types/make-dir"
    versions:
    - "> 1.0.3"
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: "@types/prettier"
    versions:
    - 2.1.6
    - 2.2.0
