language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
before_install:
  - npm install -g greenkeeper-lockfile@1
install:
  - npm install
before_script:
  - greenkeeper-lockfile-update
script:
  - npm run lint
  - npm run test -- --ci --verbose --coverage
after_success:
  - npm run semantic-release
after_script:
  - greenkeeper-lockfile-upload
