language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
install:
  - npm install
script:
  - npm run lint
  - npm run test -- --ci --verbose --coverage
after_success:
  - npm run semantic-release
