language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'node'
  - 6
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
script:
  - npm run lint
  - npm run test
after_success:
  - npm run semantic-release
after_script:
  - greenkeeper-lockfile-upload
