language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'node'
  - 6
before_script:
  - npm prune && npm cache clean --force
script:
  - npm run lint
  - npm run test
after_success:
  - npm run semantic-release
